=== PabVF23/ECW/Proyecto XML/plantilla.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.pabvf.es/plantilla"
xmlns="http://www.pabvf.es/plantilla"
elementFormDefault="qualified">
    <xs:element name="pagina">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="elemento" type="elemento" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="titulo" type="xs:string" use="required" />
            <xs:attribute name="nombre-archivo" type="xs:string" use="required" />
            <xs:attribute name="ruta-estilo" type="xs:string" use="optional" />
        </xs:complexType>
    </xs:element>

    <xs:complexType name="elemento" abstract="true"/>

    <xs:complexType name="parrafo">
        <xs:complexContent>
            <xs:extension base="elemento">
                <xs:sequence>
                    <xs:element name="contenido" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="titulo">
        <xs:complexContent>
            <xs:extension base="elemento">
                <xs:sequence>
                    <xs:element name="contenido" type="xs:string"/>
                </xs:sequence>

                <xs:attribute name="nivel" use="required">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="1"/>
                            <xs:maxInclusive value="6"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="imagen">
        <xs:complexContent>
            <xs:extension base="elemento">
                <xs:attribute name="ruta" type="xs:string" use="required"/>
                <xs:attribute name="alt" type="xs:string" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="lista">
        <xs:complexContent>
            <xs:extension base="elemento">
                <xs:sequence>
                    <xs:element name="elemento" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                </xs:sequence>

                <xs:attribute name="tipo" use="required">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="ordenada"/>
                            <xs:enumeration value="desordenada"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="seccion">
        <xs:complexContent>
            <xs:extension base="elemento">
                <xs:sequence>
                    <xs:element name="elemento" type="elemento" minOccurs="1" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>

=== PabVF23/ECW/Proyecto XML/sobremi.xml
<?xml version="1.0" encoding="UTF-8"?>
<pagina
    xmlns="http://www.pabvf.es/plantilla" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.pabvf.es/plantilla plantilla.xsd"
    titulo="Sobre mi" nombre-archivo="sobremi" ruta-estilo="../estilos/plantilla.css">
    <elemento nivel="2" xsi:type="titulo">
        <contenido>Sobre mi</contenido>
    </elemento>

    <elemento xsi:type="seccion">
        <elemento nivel="3" xsi:type="titulo">
            <contenido>Nombre y apellidos</contenido>
        </elemento>

        <elemento xsi:type="parrafo">
            <contenido>Pablo Valdés Fernández</contenido>
        </elemento>

        <elemento nivel="3" xsi:type="titulo">
            <contenido>Correo electrónico</contenido>
        </elemento>

        <elemento xsi:type="parrafo">
            <contenido>UO282655@uniovi.es</contenido>
        </elemento>

        <elemento nivel="3" xsi:type="titulo">
            <contenido>Quién soy</contenido>
        </elemento>

        <elemento xsi:type="parrafo">
            <contenido>Soy un alumno de la Universidad de Oviedo</contenido>
        </elemento>

        <elemento nivel="3" xsi:type="titulo">
            <contenido>Foto</contenido>
        </elemento>

        <elemento xsi:type="parrafo">
            <contenido>Una foto mia</contenido>
        </elemento>

        <elemento ruta="foto.png" alt="Una foto mía" xsi:type="imagen"/>
    </elemento>
</pagina>

=== PabVF23/ECW/Proyecto XML/proyectos.xml
<pagina 
    xmlns="http://www.pabvf.es/plantilla" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.pabvf.es/plantilla plantilla.xsd"
    titulo="Mis proyectos" nombre-archivo="proyectos" ruta-estilo="../estilos/plantilla.css">
    <elemento nivel="2" xsi:type="titulo">
        <contenido>Mis proyectos</contenido>
    </elemento>

    <elemento xsi:type="parrafo">
        <contenido>Una pequeña lista de mis proyectos</contenido>
    </elemento>

    <elemento tipo="desordenada" xsi:type="lista">
        <elemento>Reproductor de música</elemento>
        <elemento>Juego de la serpiente</elemento>
        <elemento>Chat Bot</elemento>
    </elemento>
</pagina>

=== PabVF23/ECW/Proyecto XML/aficiones.xml
<pagina
    xmlns="http://www.pabvf.es/plantilla" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.pabvf.es/plantilla plantilla.xsd"
    titulo="Mis aficiones" nombre-archivo="aficiones" ruta-estilo="../estilos/plantilla.css">
    <elemento nivel="2" xsi:type="titulo">
        <contenido>Mis aficiones</contenido>
    </elemento>

    <elemento xsi:type="parrafo">
        <contenido>Una pequeña lista de mis aficiones</contenido>
    </elemento>

    <elemento nivel="3" xsi:type="titulo">
        <contenido>La música</contenido>
    </elemento>

    <elemento tipo="desordenada" xsi:type="lista">
        <elemento>The Smiths</elemento>
        <elemento>Metallica</elemento>
        <elemento>Michael Jackson</elemento>
    </elemento>

    <elemento nivel="3" xsi:type="titulo">
        <contenido>El cine</contenido>
    </elemento>

    <elemento tipo="desordenada" xsi:type="lista">
        <elemento>Suspiria</elemento>
        <elemento>Amanece que no es poco</elemento>
        <elemento>La sustancia</elemento>
    </elemento>

    <elemento nivel="3" xsi:type="titulo">
        <contenido>La literatura</contenido>
    </elemento>

    <elemento tipo="desordenada" xsi:type="lista">
        <elemento>Dune</elemento>
        <elemento>Cien años de soledad</elemento>
        <elemento>A sangre fría</elemento>
    </elemento>
</pagina>
